#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : geventhttpclient-wheels
Version  : 1.3.1.dev3
Release  : 4
URL      : https://files.pythonhosted.org/packages/1a/49/558a102f9f4dab1303356b997fb39b5669455e3ef243c7feedec3c1bf274/geventhttpclient-wheels-1.3.1.dev3.tar.gz
Source0  : https://files.pythonhosted.org/packages/1a/49/558a102f9f4dab1303356b997fb39b5669455e3ef243c7feedec3c1bf274/geventhttpclient-wheels-1.3.1.dev3.tar.gz
Summary  : Pre-built wheels for geventhttpclient
Group    : Development/Tools
License  : MIT
Requires: geventhttpclient-wheels-license = %{version}-%{release}
Requires: geventhttpclient-wheels-python = %{version}-%{release}
Requires: geventhttpclient-wheels-python3 = %{version}-%{release}
Requires: certifi
Requires: gevent
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : gevent
BuildRequires : six

%description
A high performance, concurrent HTTP client library for python using gevent.
        
        gevent.httplib support was removed in gevent 1.0, geventhttpclient now
        provides that missing functionality.
        
        geventhttpclient uses a fast http parser, written in C, originating from
        nginx, extracted and modified by Joyent.
        
        geventhttpclient has been specifically designed for high concurrency,
        streaming and support HTTP 1.1 persistent connections. More generally it is
        designed for efficiently pulling from REST APIs and streaming APIs
        like Twitter's.
        
        Safe SSL support is provided by default. geventhttpclient depends on
        the certifi CA Bundle. This is the same CA Bundle which ships with the
        Requests codebase, and is derived from Mozilla Firefox's canonical set.
        
        Python 2.7 and 3.4+ are supported.
        Python 2.6 is no longer supported.
        
        Use of SSL/TLS with python 2.7.9 is not recommended and may be broken.

%package license
Summary: license components for the geventhttpclient-wheels package.
Group: Default

%description license
license components for the geventhttpclient-wheels package.


%package python
Summary: python components for the geventhttpclient-wheels package.
Group: Default
Requires: geventhttpclient-wheels-python3 = %{version}-%{release}

%description python
python components for the geventhttpclient-wheels package.


%package python3
Summary: python3 components for the geventhttpclient-wheels package.
Group: Default
Requires: python3-core
Provides: pypi(geventhttpclient_wheels)
Requires: pypi(certifi)
Requires: pypi(gevent)
Requires: pypi(six)

%description python3
python3 components for the geventhttpclient-wheels package.


%prep
%setup -q -n geventhttpclient-wheels-1.3.1.dev3
cd %{_builddir}/geventhttpclient-wheels-1.3.1.dev3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586981369
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/geventhttpclient-wheels
cp %{_builddir}/geventhttpclient-wheels-1.3.1.dev3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/geventhttpclient-wheels/a6751b809f6837cdb0240746a1ea2b328a385e8a
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/geventhttpclient-wheels/a6751b809f6837cdb0240746a1ea2b328a385e8a

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
